version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lazada-game-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env # โหลด secret จากไฟล์ .env (ไม่ push ขึ้น GitHub)
    networks:
      - backend
    restart: unless-stopped
    environment:
      TZ: Asia/Bangkok

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
    name: lazada-game_backend
